name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello, thank you for time. Please make sure the issue is not environment specific. If this is a security issue please email jeremykenedy@gmail.com'
          pr-message: '👋 Thank you for contributing. Your PR will be reviewed and if all is good it will be merged in. Thank you again ❤️'
