name: Generate Release Notes

steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3.2.0
    with:
      semantic_version: 18
      extra_plugins: |
        @semantic-release/changelog
        @semantic-release/git
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
